### ISSUE TITLE
Outline and Begin to draft a narrative for CSTEMBE if they partner with us (Section 3)

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/learning-pathways-whitepaper#12]

**Comment by omnignorant** [comment]
[Started a draft narrative](https://docs.google.com/a/mozillafoundation.org/document/d/1xqPW8phSQ_kaKXrMVKf8y1Ol2mc1OORasEp8YgJt5h4/edit#heading=h.6u7tn1w8p4mf) but this will need a lot more work. Currently 2 paragraphs and an outline. @dajbelshaw is this on the right track?
