### ISSUE TITLE
Talk about visuals with Jess

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/learning-pathways-whitepaper#26]
Need to arrange coversation with @iamjessklein

**Comment by dajbelshaw** [comment]
Arranged to meet via Skype at 11:30 ET on Monday 2nd March. Pathways whitepaper is here: http://goo.gl/yB5FFB 

/ cc @smithisgeneric @omnignorant (please do join if you can make it!)

**Comment by dajbelshaw** [comment]
@iamjessklein informed me she's begun work on this in this. :)

**Comment by smithisgeneric** [comment]
I'd love a status update from @iamjessklein on where she got to on this.  

There are 4 spots in the whitepaper draft where an "insert graphic" note exists in the text https://docs.google.com/document/d/1xqPW8phSQ_kaKXrMVKf8y1Ol2mc1OORasEp8YgJt5h4/edit#

I need to take over as driver here with Doug's transition.  I need at least 2 heartbeats to wrap up with my current workload.
